import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
// import LoginForm from "./components/LoginForm"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        
        <div className='flex justify-center m-2' >
          
          <Link className="m-3" href="/">Garage List</Link>
          <Link href="/management">Create Garage Inventory</Link>
        </div>

        {children}

      </body>
    </html>
  );
}

